<?php
/**
 * @file
 * Funkcja symuluje bipniecie przez zapis komunikatu do dziennika Drupala
 */
function beep_beep()
{
    watchdog('beep','Bip!');
}




/**
 * wybierz wyzwalacze ktore maja byc powiazane z dzialaniem
 * Implements hook_action_info().
 */
function beep_action_info()
{
    return [
      'beep_single_beep_action' => [
          'type' => 'system',
          'label' => t('Uporczywe brzęczenie'),
          'configurable' => false,
          'triggers' => [
              'node_view','node_insert','node_update','node_delete',
              //'any'
          ]
      ],
      'beep_multiple_beep_action' => [
          'type' => 'system',
          'label' => t('Brzeczenie wielokrotne'),
          'configurable' => true,
          'triggers' => [
             'node_view','node_insert','node_update','node_delete',

          ]
      ]
    ];
}

/**
 * Formularz ​konfigurowalnego ​działania ​— ​wielokrotne ​bipnięcie.
 */
function beep_multiple_beep_action_form($context)
{
    $form['beeps'] = [
        '#type' => 'textfield',
        '#title' => t('Liczba bipnięć'),
        '#description' => t('Wprowadz liczbę bipnięc'),
        '#default_value' => isset($context['beeps'])?$context['beeps']:'1',
        '#required' => true
    ];
    return $form;
}

/**
 * walidacja forma
 */
function beep_multiple_beep_action_validate($form,$form_state)
{
    $beeps = $form_state['values']['beeps'];

    if ((int) $beeps<0 && $beeps>10) {
        form_set_error('beeps',t('Wprowadź liczbę całkowitą od 0..1'));
    }
    else if ((int) $beeps>10) {
        form_set_error('beeps',t('Nie przesadzaj max to 10'));
    }
    else if ((int) $beeps <0) {
        form_set_error('beeps',t('Liczba nie moze byc mniejsza od 0'));
    }

}

function beep_multiple_beep_action_submit($form, $form_state)
{
    return [
        'beeps' => (int) $form_state['values']['beeps']
    ];
}



/**
 * symuluj bipniecie.
 */
function beep_single_beep_action()
{
    beep_beep();
}

function beep_multiple_beep_action($object, $context)
{
    for ($i=0; $i< $context['beeps']; $i++) {
        beep_beep();
    }
}

