<?php
/**
 * Implements hook_node_info().
 */
function job_post_node_info()
{
    return [
        'job_post' => [
            'name' => t('Ogłoszenia o prace'),
            'base' => 'job_post',
            'description' => t('Ten rodzaj zawartości pozwala na wysyłanie ogłoszeń o prace'),
            'has_title' => true,
            'help' => t('Wprowadz stanowisko opis obowiazkow i nazwe firmy ktora wysyla ogloszenie')
        ]
    ];
}

function job_post_form($node,$form_state)
{
    return node_content_form($node,$form_state);
}

/**
 * Implements hook_menu_alter().
 */
function job_post_menu_alter(&$items)
{
    //jesli user nie ma uprawnien administer nodes, wylacz element menu job_post, ustawiajc atrybut access callback na wartosc false
    if (!user_access('administer nodes')) {
        $items['node/add/job_post']['access callback'] = false;
        //usun arguemnty dostepu gdyz inaczej drupal skorzysta z funkcji user_access jako domyslnego wywolania zwrotnego dostepu
        unset($items['node/add/job_post']['access arguemnts']);
    }
}

/**
 * iMplementacja haka hook_permission
 */
function job_post_permission()
{
    return [
      'create job post' => [
          'title' => t('Utworz oglosznie o prace'),
          'description' => t('Utworz ogłoszenie o prace')
      ],
      'edit own job post' => [
          'title' => t('Edytuj swoje ogłosznie o prace'),
          'description' => t('Edytuj swoje ogłosznie o prace')
      ],
      'delete own job post' => [
          'title' => t('Usuń swoje ogłoszenie o prace'),
          'description' => t('Usuń swoje ogłoszenie o prace')
      ],
      'delete any job post' => [
          'title' => t('Usuń dowolne ogłoszenie o prace'),
          'description' => t('Usuń dowolne ogłosznie o prace')
      ]
    ];
}

/**
 * Implements hook_node_access().
 */
function job_post_node_access($node, $op, $account)
{

    $is_author = @$account->uid == @$node->uid;


    switch ($op) {
        case 'create':
            //zezwol jesli user ma uprawnienei create job post
            if (user_access('create_job_post',$account)) {
                return NODE_ACCESS_ALLOW;
            }
        CASE 'update':
            //zezwol jesli user ma upr edit own job post i jest autorem segmentu i ma uprawnienei edit any job
            if (user_access('edit own job post',$account) && $is_author || user_access('edit any job post',$account)) {
                return NODE_ACCESS_ALLOW;
            }
        CASE 'delete':
            //zezwol jesli user ma upr delete own job post i jest autorem segmentu  lub ma upr any job
            if (user_access('delete own job post',$account) && $is_author || user_access('delete any job post',$account)) {
                return NODE_ACCESS_ALLOW;
            }
    }

}

function job_post_validate($node)
{
    //ustaw ogranicznie minimalnej liczby znakow w nazwie firmy na 2

    if (isset($node->job_post_company) && strlen($node->job_post_company['und'][0]['value']) < 2) {
        form_set_error('job_post_comapny',t('Nazwa firmy jest za krótka min 2 znaki'),null);
    }
}


/**
 * Implementacja hooka hook_insert hook jest zalezny od huka job_post_node_info index job_post i dopisuje insert i daje nam job_post_insert
 */

/**
 * Implements hook_insert().
 */
function job_post_insert($node)
{
    //zglos szczegoly ogloszenia o prace do tabeli watchdog
    watchdog('job post','Dodano nowe ogłoszenie o pracy zatytułowane: '
        .$node->title.' dla firmy '.$node->job_post_company['und'][0]['value']
        .' zostało utworzone przez usera o id '.$node->uid,$variables = [],WATCHDOG_NOTICE,$link = 'node/'.$node->nid);
}

function job_post_update($node) {
    //zapisz szegoly
    watchdog('job post','Dodano nowe ogłoszenie o pracy zatytułowane: '
        .$node->title.' dla firmy '.$node->job_post_company['und'][0]['value']
        .' zostało utworzone przez usera o id '.$node->uid,$variables = [],WATCHDOG_NOTICE);
}


function job_post_delete($node)
{
    watchdog('job post','Dodano nowe ogłoszenie o pracy zatytułowane: '
        .$node->title.' dla firmy '.$node->job_post_company['und'][0]['value']
        .' zostało utworzone przez usera o id '.$node->uid,$variables = [],WATCHDOG_NOTICE,$link = 'node/'.$node->nid);
}

/**
 * @param $nodes
 * @return mixed
 * Dodanie sponor w chwili ładowania obiektu job_post
 */
function job_post_load($nodes)
{
    //Dodaj do segmentu w moemencie ładowania nowy atrybut informacje na temat sponsora
    foreach ($nodes as $node) {
        $node->sponsor = "ACME Agencja pośrednica Pracy, Twoje źródło ofert pracy Drupala";
    }
    return $node;
}

/**
 * Implements hook_view().
 */
function job_post_view($node, $view_mode, $langcode = NULL)
{
    //Dodaj i przygotuj do rednerowani ainformacje o sponsorze dzieki czemu zostanie ona wyswietlona wraz z ogloszeniem o pracy

    if ($view_mode=='full') {
        $node->content['sponsor'] = [
          '#markup' => theme('sponsor',['sponsor'=>$node->sponsor,'sponsor_id'=>$node->nid]),
          '#weight' => 100
        ];

    }
    return $node;
}

function job_post_theme()
{
    //zdefiniuj zmienne i szablon zwiazane z polem sponsora. Wyswietlona bedzie nazwa sponsora natomiast jeg identyfikator
    //zostanie wykorzystany do utworzenia unikalnego id w plikach css
    return [
      'sponsor' => [
          'variables' => [
              'sponsor'=>null,'sponsor_id'=>null
          ],
          'template' => 'sponsor'

      ],
      'mydescription' => [
        'variables' => [
            'mydescription'=>null
        ],
        'template' => 'mydescription'

      ]
    ];
}


function job_post_node_load($nodes)
{
    //Dodaj do segmentu w moemencie ładowania nowy atrybut informacje na temat sponsora
    foreach ($nodes as $node) {
        $node->mydescription = "Dypdafa fldaksjflkadsjf lsadlfjkldsaflkjsadlfs";
    }
    return $node;
}
function job_post_node_view($node, $view_mode, $langcode)
{
    if ($view_mode=='full') {
        $node->content['mydescription'] = [
            '#markup' => theme('mydescription',['mydescription'=>$node->mydescription]),
            '#weight' => 100
        ];

    }
    return $node;
}
