<?php
/**
 * @file
 *
 */




/**
 * Implements hook_menu().
 */
function bunny_menu()
{
    $items['bunny'] = [
        'title' => 'Farma królików',
        'access callback' => true,
        'page callback' => 'bunny_overview',
        'type' => MENU_NORMAL_ITEM
    ];

    $items['bunny/list'] = [
        'title' => 'Lista królików',
        'access callback' => true,
        'type' => MENU_DEFAULT_LOCAL_TASK,
        'weight' => 0
    ];

    $items['bunny/add'] = [
        'title' => 'Dodaj królika',
        'access callback' => true,
        'page callback' => 'bunny_add',

        'type' => MENU_LOCAL_TASK,
        'weight' => 1

    ];

    return $items;

}

function bunny_overview()
{
    global $user;
    $output = null;
    if (user_is_logged_in()) {
        $output = 'Witaj: ' . $user->name . '<br />';
    }
    $query = db_select('bunnies','b');

    $query->fields('b',['name','bid','tons']);
    $query->orderBy('name','asc');
    $query = $query->extend('PagerDefault')->limit(5);

    $result = $query->execute();

    foreach ($result as $row) {
        $output .= $row->bid.' - '.$row->name.' waga: '.$row->tons.' <br>';
    }
    $output .= theme('pager');
    return $output;
}

function bunny_add()
{
    //add new record
    $table = 'bunnies';
    $record = new stdClass();
    $record->name = 'Królik'.rand(0,1000);
    $record->tons = rand(1,10);
    drupal_write_record($table,$record);
    watchdog('bunny','Dodano nowego królika o id %id',['%id'=>$record->bid]);
    drupal_goto('bunny/list');
    return t('dodaje królika');


    //edit record

    //$record->name = 'jakies zmienione imie';
    //drupal_write_record($table,$record,'bid');
}