<?php
/**
 * @file
 *
 */

/**
 * Add field to config file
 */
/**
 * Implements hook_menu().
 */
function current_post_menu()
{
    $items = [];
    $items['admin/config/content/current_post'] = [
      'title' =>t('Current post'),
      'description' => t('Configuration for current post module'),
      'page callback' => 'drupal_get_form',
      'page arguments' => ['current_post_form'],
      'access arguments' => ['access administration page']
    ];

    return $items;
}


/**
 * Page callback: Current posts settings
 *
 * @see current_posts_menu()
 */
function current_post_form($form, &$form_state)
{
    $form['current_post'] = [
      '#type' => 'fieldset',
      '#title' => t('Maximum number of post'),

      '#description' =>t('The maximum number of links to display in the block'),
    ];

    $form['current_post']['max_field'] =[
        '#type' => 'textfield',
        '#title' => t('Enter the number'),
        '#default_value' => variable_get('max_field',3),
        '#size' => 2,
        '#maxlength' => 2,
        '#required' =>true
    ];

   // $form['#submit'][] = 'current_post_form_submit';
    return system_settings_form($form);
}


function current_post_form_validate($form,&$form_state)
{

    $max_num = $form_state['values']['max_field'];

    if (!is_numeric($max_num)) {
        form_set_error('max_field', t('You must enter a number for the maximum number of posts to display.'));
    } elseif ($max_num <= 0){
        form_set_error('max_field', t('Maximum number of posts to display must be positive.'));
    } elseif ($max_num >50) {
        form_set_error('max_field', t('Maximum number of post not > 100'));
    }
}

