<?php
/**
 * @file
 */

/**
 * Implements hook_block_info().
 */
function my_theme_block_block_info()
{
    $block['mycustomblock'] = [
        'info' => t('Moj zajefajny block'),
        'status' => true,
        'region' => 'content',
        'weight' => 0,
        'visibility' => 1
    ];

    return $block;
}

/**
 * Implements hook_block_configure().
 */
function my_theme_block_block_configure($delta = '')
{
    $form = [];
    switch ($delta) {
        case 'mycustomblock':
        {
            $form['mycustomblock_person'] = [
                '#type' => 'textfield',
                '#title' => t('Wprowadź Imię'),
                '#size' => 20,
                '#description' => t('Wprowadź Imię'),
                '#default_value' => variable_get('mycustomblock_person','Adam')
            ];
            break;
        }


    }
    return $form;
}



/**
 * Implements hook_block_save().
 */
function my_theme_block_block_save($delta = '', $edit = array())
{

        switch ($delta) {
            case 'mycustomblock':
                variable_set('mycustomblock_person',$edit['mycustomblock_person']);
                break;

        }

}

function my_theme_block_block_view($delta = '')
{
    switch ($delta) {
        case 'mycustomblock':
            $block['subject'] = t('Mój zajefajny block');
            $block['person'] = variable_get('mycustomblock_person');
            $block['list'] = ['Adam','Maciek','Krzysiek'];
            $block['content'] = my_theme_block_block_contents($block,$delta);
            return $block;
            break;


    }
}

function my_theme_block_block_contents($block,$delta)
{
    switch ($delta) {
        case 'mycustomblock':
            return ['#markup' => theme('custom_view', ['mycustomblock' => $block])];
    }
}

function my_theme_block_theme()
{
    return [
        'custom_view' => [
            'variables' => [
                'mycustomblock' => null,
            ],
            'template' => 'custom_view'
        ]


    ];
}